### ISSUE TITLE
Maybe we can add more atom-style icons?

### ISSUE THREAD

**Issue by ghsgz** [emroussel/atom-icons#1]
Hi, @emroussel , I like your atomize extensions because I like atom's UI and UX too. Thanks for your great work!

I downloaded your this extension today and find that the number of the icon is minimal, and I found that [the latest Atom](https://atom.io/) has owned more rich icons with the same style. So, maybe we can include those icons into this extension?

![atom-icons](https://user-images.githubusercontent.com/34056529/72206637-5fe3ee00-34cb-11ea-81a1-61f424ef2b4a.png)

**Comment by ghsgz** [comment]
I just installed the latest Atom and found the icons of Atom are the same as atom-icons. The picture above may be a well-designed work of some employee of GitHub.

I will close this issue. Thanks for your work again! :beer:

**Comment by emroussel** [comment]
No problem, don't hesitate to open another issue if you have more suggestions!
