### ISSUE TITLE
Way to hide or change opacity of arrows in file explorer?

### ISSUE THREAD

**Issue by MikeJMontgomery** [emroussel/atom-icons#5]
Would be great to be able to do this. Thanks!

**Comment by emroussel** [comment]
Hey @MikeJMontgomery, it looks like VS Code allows people to override these type of icons through [product icon themes](https://code.visualstudio.com/api/extension-guides/product-icon-theme), but it's still in preview. This theme only changes the file icons. I might consider expanding it (or creating a new one) to provide product icons later on, but will definitely wait for the API to be released and stable first.

You can always create your own product icon theme to do this.
