### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by delucca** [emroussel/atom-icons#6]
Hi everyone :)

Amazing job you've done in this package! I love Atom style and moved recently to VSCode. This extension, in my opinion, is the best icon theme there is for VSCode

Anyway, I'm trying Gitpod, and it is based on VSCode on it's editor, so we can install any VSCode extension in it (more about that [here](https://www.gitpod.io/docs/vscode-extensions/)).

To install a VSCode extension, we need to publish it on [OpenVSX](https://open-vsx.org/)

Can you please publish your extension there? :)

Thanks!

**Comment by emroussel** [comment]
Thanks for the kind words @delucca!

I published this extension (as well as the matching color theme, [Atomize](https://github.com/emroussel/atomize)) to open-vsx. You can find them here:

- https://open-vsx.org/extension/emroussel/atom-icons
- https://open-vsx.org/extension/emroussel/atomize-atom-one-dark-theme

Don't hesitate to let me know if you're running into any issues using them on Gitpod.
